a = input().split()
b = int(a[0])+int(a[1])
c = a[0].replace('5','6')
d = a[1].replace('5','6')
e = a[0].replace('6','5')
f = a[1].replace('6','5')
g = int(c)+int(d)
h = int(e)+int(f)
print(min([b,g,h]),max([b,g,h]))